export type CountryName =
  | "Afghanistan"
  | "Albania"
  | "Algeria"
  | "American Samoa"
  | "Andorra"
  | "Angola"
  | "Anguilla"
  | "Antarctica"
  | "Antigua and Barbuda"
  | "Argentina"
  | "Armenia"
  | "Aruba"
  | "Australia"
  | "Austria"
  | "Azerbaijan"
  | "Bahamas"
  | "Bahrain"
  | "Bangladesh"
  | "Barbados"
  | "Belarus"
  | "Belgium"
  | "Belize"
  | "Benin"
  | "Bermuda"
  | "Bhutan"
  | "Bolivia"
  | "Bosnia and Herzegovina"
  | "Botswana"
  | "Bouvet Island"
  | "Brazil"
  | "British Indian Ocean Territory"
  | "Brunei Darussalam"
  | "Bulgaria"
  | "Burkina Faso"
  | "Burundi"
  | "Cambodia"
  | "Cameroon"
  | "Canada"
  | "Cape Verde"
  | "Cayman Islands"
  | "Central African Republic"
  | "Chad"
  | "Chile"
  | "People's Republic of China"
  | "China"
  | "Christmas Island"
  | "Cocos (Keeling) Islands"
  | "Colombia"
  | "Comoros"
  | "Republic of the Congo"
  | "Congo"
  | "Democratic Republic of the Congo"
  | "Cook Islands"
  | "Costa Rica"
  | "Cote d'Ivoire"
  | "Côte d'Ivoire"
  | "Ivory Coast"
  | "Croatia"
  | "Cuba"
  | "Cyprus"
  | "Czech Republic"
  | "Czechia"
  | "Denmark"
  | "Djibouti"
  | "Dominica"
  | "Dominican Republic"
  | "Ecuador"
  | "Egypt"
  | "El Salvador"
  | "Equatorial Guinea"
  | "Eritrea"
  | "Estonia"
  | "Ethiopia"
  | "Falkland Islands (Malvinas)"
  | "Faroe Islands"
  | "Fiji"
  | "Finland"
  | "France"
  | "French Guiana"
  | "French Polynesia"
  | "French Southern Territories"
  | "Gabon"
  | "Republic of The Gambia"
  | "The Gambia"
  | "Gambia"
  | "Georgia"
  | "Germany"
  | "Ghana"
  | "Gibraltar"
  | "Greece"
  | "Greenland"
  | "Grenada"
  | "Guadeloupe"
  | "Guam"
  | "Guatemala"
  | "Guinea"
  | "Guinea-Bissau"
  | "Guyana"
  | "Haiti"
  | "Heard Island and McDonald Islands"
  | "Holy See (Vatican City State)"
  | "Honduras"
  | "Hong Kong"
  | "Hungary"
  | "Iceland"
  | "India"
  | "Indonesia"
  | "Islamic Republic of Iran"
  | "Iran"
  | "Iraq"
  | "Ireland"
  | "Israel"
  | "Italy"
  | "Jamaica"
  | "Japan"
  | "Jordan"
  | "Kazakhstan"
  | "Kenya"
  | "Kiribati"
  | "North Korea"
  | "South Korea"
  | "Korea, Republic of"
  | "Republic of Korea"
  | "Kuwait"
  | "Kyrgyzstan"
  | "Lao People's Democratic Republic"
  | "Latvia"
  | "Lebanon"
  | "Lesotho"
  | "Liberia"
  | "Libya"
  | "Liechtenstein"
  | "Lithuania"
  | "Luxembourg"
  | "Macao"
  | "Madagascar"
  | "Malawi"
  | "Malaysia"
  | "Maldives"
  | "Mali"
  | "Malta"
  | "Marshall Islands"
  | "Martinique"
  | "Mauritania"
  | "Mauritius"
  | "Mayotte"
  | "Mexico"
  | "Micronesia, Federated States of"
  | "Moldova, Republic of"
  | "Monaco"
  | "Mongolia"
  | "Montserrat"
  | "Morocco"
  | "Mozambique"
  | "Myanmar"
  | "Namibia"
  | "Nauru"
  | "Nepal"
  | "Netherlands"
  | "The Netherlands"
  | "Netherlands (Kingdom of the)"
  | "New Caledonia"
  | "New Zealand"
  | "Nicaragua"
  | "Niger"
  | "Nigeria"
  | "Niue"
  | "Norfolk Island"
  | "The Republic of North Macedonia"
  | "North Macedonia"
  | "Northern Mariana Islands"
  | "Norway"
  | "Oman"
  | "Pakistan"
  | "Palau"
  | "State of Palestine"
  | "Palestine"
  | "Panama"
  | "Papua New Guinea"
  | "Paraguay"
  | "Peru"
  | "Philippines"
  | "Pitcairn"
  | "Pitcairn Islands"
  | "Poland"
  | "Portugal"
  | "Puerto Rico"
  | "Qatar"
  | "Reunion"
  | "Romania"
  | "Russian Federation"
  | "Russia"
  | "Rwanda"
  | "Saint Helena"
  | "Saint Kitts and Nevis"
  | "Saint Lucia"
  | "Saint Pierre and Miquelon"
  | "Saint Vincent and the Grenadines"
  | "Samoa"
  | "San Marino"
  | "Sao Tome and Principe"
  | "Saudi Arabia"
  | "Senegal"
  | "Seychelles"
  | "Sierra Leone"
  | "Singapore"
  | "Slovakia"
  | "Slovenia"
  | "Solomon Islands"
  | "Somalia"
  | "South Africa"
  | "South Georgia and the South Sandwich Islands"
  | "Spain"
  | "Sri Lanka"
  | "Sudan"
  | "Suriname"
  | "Svalbard and Jan Mayen"
  | "Eswatini"
  | "Sweden"
  | "Switzerland"
  | "Syrian Arab Republic"
  | "Taiwan"
  | "Tajikistan"
  | "United Republic of Tanzania"
  | "Tanzania"
  | "Thailand"
  | "Timor-Leste"
  | "Togo"
  | "Tokelau"
  | "Tonga"
  | "Trinidad and Tobago"
  | "Tunisia"
  | "Türkiye"
  | "Turkey"
  | "Turkmenistan"
  | "Turks and Caicos Islands"
  | "Tuvalu"
  | "Uganda"
  | "Ukraine"
  | "United Arab Emirates"
  | "UAE"
  | "United Kingdom"
  | "UK"
  | "Great Britain"
  | "United States of America"
  | "United States"
  | "USA"
  | "U.S.A."
  | "US"
  | "U.S."
  | "United States Minor Outlying Islands"
  | "Uruguay"
  | "Uzbekistan"
  | "Vanuatu"
  | "Venezuela"
  | "Vietnam"
  | "Virgin Islands, British"
  | "Virgin Islands, U.S."
  | "Wallis and Futuna"
  | "Western Sahara"
  | "Yemen"
  | "Zambia"
  | "Zimbabwe"
  | "Åland Islands"
  | "Aland Islands"
  | "Bonaire, Sint Eustatius and Saba"
  | "Curaçao"
  | "Guernsey"
  | "Isle of Man"
  | "Jersey"
  | "Montenegro"
  | "Saint Barthélemy"
  | "Saint Martin (French part)"
  | "Serbia"
  | "Sint Maarten (Dutch part)"
  | "South Sudan"
  | "Kosovo"
  | "Zero Knowledge Republic"
